INSERT INTO rulesets (_id, sharedAllowancePence, startDate, endDate, notes) VALUES ('2017/2018', 2000000, '2017-04-06', '2018-04-05', NULL);
INSERT INTO rulesets (_id, sharedAllowancePence, startDate, endDate, notes) VALUES ('2018/2019', 2000000, '2018-04-06', '2019-04-05', 'The Junior ISA allowance was increased by £132/year (£11/month) in line with inflation.');
INSERT INTO rulesets (_id, sharedAllowancePence, startDate, endDate, notes) VALUES ('2019/2020', 2000000, '2019-04-06', '2020-04-05', 'The Junior ISA allowance was increased by £108/year (£9/month) in line with inflation.');
INSERT INTO rulesets (_id, sharedAllowancePence, startDate, endDate, notes) VALUES ('2020/2021', 2000000, '2020-04-06', '2021-04-05', 'The Junior ISA allowance was increased by £4,632/year (£386/month). The LISA withdrawal charge was reduced from 25% to 20% for withdrawals made between 6th March 2020 and 5th April 2021.');
INSERT INTO rulesets (_id, sharedAllowancePence, startDate, endDate, notes) VALUES ('2021/2022', 2000000, '2021-04-06', '2022-04-05', 'There were no changes to ISAs this year.');
INSERT INTO rulesets (_id, sharedAllowancePence, startDate, endDate, notes) VALUES ('2022/2023', 2000000, '2022-04-06', '2023-04-05', 'There were no changes to ISAs this year.');
INSERT INTO rulesets (_id, sharedAllowancePence, startDate, endDate, notes) VALUES ('2023/2024', 2000000, '2023-04-06', '2024-04-05', 'There were no changes to ISAs this year.');
INSERT INTO rulesets (_id, sharedAllowancePence, startDate, endDate, notes) VALUES ('2024/2025', 2000000, '2024-04-06', '2025-04-05', 'Fractional share contracts were added to the eligble investments within Stocks and Shares, Junior and Lifetime ISAs. It is now permissible to open and pay into multiple of the same type of ISAs in the same year, with Lifetime ISAs and Junior ISAs excepted. The minimum age for opening an ISA increased from 16 to 18. Partial transfers of ISA contributions were introduced. There were no changes to allowances for ISAs and allowances for all ISA types were frozen until the 2030/2031 tax year.');
INSERT INTO rulesets (_id, sharedAllowancePence, startDate, endDate, notes) VALUES ('2025/2026', 2000000, '2025-04-06', '2026-04-05', 'Long-Term Asset Funds were added to the eligible investments within Innovative Fund ISAs. A National Insurance number is now required to be provided to open an ISA, unless ineligible. There were no changes to allowances.');
INSERT INTO productTypes (_id, name, introducedWithRuleset, removedWithRuleset, shortDescription, longDescription) VALUES ('CASH', 'Cash ISA', '2008/2009', NULL, 'Earn interest on cash tax-free', 'A deposit account, where your cash is guaranteed. The rules for accessing the cash once deposited may differ by account.');
INSERT INTO productTypes (_id, name, introducedWithRuleset, removedWithRuleset, shortDescription, longDescription) VALUES ('STOCKS_AND_SHARES', 'Stocks & Shares ISA', '2008/2009', NULL, 'Invest without paying tax on gains', 'A number of investment structures in a tax-free wrapper. Income and gains from the investments in the accounts are not subject to dividend, income or capital gains taxes.');
INSERT INTO productTypes (_id, name, introducedWithRuleset, removedWithRuleset, shortDescription, longDescription) VALUES ('INNOVATIVE_FINANCE', 'Innovative Finance ISA', '2016/2017', NULL, 'Profit from peer-to-peer lending, tax-free', 'An account with a peer-to-peer lending provider with a tax-free wrapper. Interest earned from providing high-risk loans are earned tax-free.');
INSERT INTO productTypes (_id, name, introducedWithRuleset, removedWithRuleset, shortDescription, longDescription) VALUES ('LIFETIME', 'Lifetime ISA', '2017/2018', NULL, 'Get rewarded for saving for your first home (or retirement)', 'A Cash or Stocks & Shares ISA with age and spend limitations, in exchange for a 25% bonus provided by the Government when withdrawing for the purchase of a first home, after turning 60 years old, when diagnosed with a terminal illness.');
INSERT INTO productTypes (_id, name, introducedWithRuleset, removedWithRuleset, shortDescription, longDescription) VALUES ('JUNIOR', 'Junior ISA', '2011/2012', NULL, 'Save for your child''s future', 'A Cash or Stocks & Shares ISA held in a child''s name. Money cannot be withdrawn until they turn 18, or in if diagnosed with a terminal illness.');
INSERT INTO productTypes (_id, name, introducedWithRuleset, removedWithRuleset, shortDescription, longDescription) VALUES ('HELP_TO_BUY', 'Help To Buy ISA', '2015/2016', '2019/2020', 'Save up for your first home and earn a government bonus', 'A Cash ISA with a monthly top-up restriction that, if used towards the purchase of your first home, will be topped up with a 25% government bonus.');
INSERT INTO providers (_id, name, iconRelativeUrl, colour) VALUES ('PLACEHOLDER', 'Other', 'https://static-assets.isaeye.uk/default-bank-icons/placeholder.svg', '#333333');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('PLACEHOLDER-0', 'building society', 'PLACEHOLDER');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('PLACEHOLDER-1', 'credit union', 'PLACEHOLDER');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('PLACEHOLDER-2', 'bs', 'PLACEHOLDER');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('PLACEHOLDER-3', 'misc', 'PLACEHOLDER');
INSERT INTO providers (_id, name, iconRelativeUrl, colour) VALUES ('abbey', 'Abbey National', 'https://static-assets.isaeye.uk/default-bank-icons/abbey.svg', '#cc2229');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('abbey-0', 'abbey', 'abbey');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('abbey-1', 'santander', 'abbey');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('abbey-2', 'abbey road', 'abbey');
INSERT INTO providers (_id, name, iconRelativeUrl, colour) VALUES ('aegon', 'Aegon', 'https://static-assets.isaeye.uk/default-bank-icons/aegon.svg', '#0168b2');
INSERT INTO providers (_id, name, iconRelativeUrl, colour) VALUES ('al-rayan', 'Al Rayan Bank', 'https://static-assets.isaeye.uk/default-bank-icons/al-rayan.svg', '#bd955a');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('al-rayan-0', 'al rayan', 'al-rayan');
INSERT INTO providers (_id, name, iconRelativeUrl, colour) VALUES ('aldermore', 'Aldermore', 'https://static-assets.isaeye.uk/default-bank-icons/aldermore.svg', '#ffda00');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('aldermore-0', 'ruffler', 'aldermore');
INSERT INTO providers (_id, name, iconRelativeUrl, colour) VALUES ('alliance-and-leicester', 'Alliance & Leicester', 'https://static-assets.isaeye.uk/default-bank-icons/alliance-and-leicester.svg', '#0055a0');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('alliance-and-leicester-0', 'a&l', 'alliance-and-leicester');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('alliance-and-leicester-1', 'alliance + leicester', 'alliance-and-leicester');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('alliance-and-leicester-2', 'alliance', 'alliance-and-leicester');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('alliance-and-leicester-3', 'leicester', 'alliance-and-leicester');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('alliance-and-leicester-4', 'santander', 'alliance-and-leicester');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('alliance-and-leicester-5', 'girobank', 'alliance-and-leicester');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('alliance-and-leicester-6', 'alliance leicester', 'alliance-and-leicester');
INSERT INTO providers (_id, name, iconRelativeUrl, colour) VALUES ('allica', 'Allica', 'https://static-assets.isaeye.uk/default-bank-icons/allica.svg', '#001c33');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('allica-0', 'allica', 'allica');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('allica-1', 'allied irish', 'allica');
INSERT INTO providers (_id, name, iconRelativeUrl, colour) VALUES ('allied-irish', 'Allied Irish Bank', 'https://static-assets.isaeye.uk/default-bank-icons/allied-irish.svg', '#7e2f7a');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('allied-irish-0', 'aib', 'allied-irish');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('allied-irish-1', 'irish bank', 'allied-irish');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('allied-irish-2', 'allied irish', 'allied-irish');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('allied-irish-3', 'first trust', 'allied-irish');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('allied-irish-4', 'provincial bank of ireland', 'allied-irish');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('allied-irish-5', 'royal bank of ireland', 'allied-irish');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('allied-irish-6', 'munster & leinster', 'allied-irish');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('allied-irish-7', 'munster + leinster', 'allied-irish');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('allied-irish-8', 'belfast banking company', 'allied-irish');
INSERT INTO providers (_id, name, iconRelativeUrl, colour) VALUES ('anglo-irish', 'Anglo Irish', 'https://static-assets.isaeye.uk/default-bank-icons/anglo-irish.svg', '#8a1d03');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('anglo-irish-0', 'ibrc', 'anglo-irish');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('anglo-irish-1', 'anglo', 'anglo-irish');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('anglo-irish-2', 'irish nationwide', 'anglo-irish');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('anglo-irish-3', 'irish bank resolution', 'anglo-irish');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('anglo-irish-4', 'aib', 'anglo-irish');
INSERT INTO providers (_id, name, iconRelativeUrl, colour) VALUES ('arbuthnot-latham', 'Arbuthnot Latham', 'https://static-assets.isaeye.uk/default-bank-icons/arbuthnot-latham.svg', '#002d59');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('arbuthnot-latham-0', 'arbuthnot', 'arbuthnot-latham');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('arbuthnot-latham-1', 'aitken hume', 'arbuthnot-latham');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('arbuthnot-latham-2', 'hume', 'arbuthnot-latham');
INSERT INTO providers (_id, name, iconRelativeUrl, colour) VALUES ('atom', 'Atom', 'https://static-assets.isaeye.uk/default-bank-icons/atom.svg', '#3c1053');
INSERT INTO providers (_id, name, iconRelativeUrl, colour) VALUES ('aviva', 'Aviva', 'https://static-assets.isaeye.uk/default-bank-icons/aviva.svg', '#fcca12');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('aviva-0', 'norwich union', 'aviva');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('aviva-1', 'direct line', 'aviva');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('aviva-2', 'aig', 'aviva');
INSERT INTO providers (_id, name, iconRelativeUrl, colour) VALUES ('axa', 'AXA', 'https://static-assets.isaeye.uk/default-bank-icons/axa.svg', '#00008f');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('axa-0', 'acksa', 'axa');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('axa-1', 'a x a', 'axa');
INSERT INTO providers (_id, name, iconRelativeUrl, colour) VALUES ('bank-of-ireland-uk', 'Bank of Ireland', 'https://static-assets.isaeye.uk/default-bank-icons/bank-of-ireland-uk.svg', '#0000ff');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('bank-of-ireland-uk-0', 'boi', 'bank-of-ireland-uk');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('bank-of-ireland-uk-1', 'banc na héireann', 'bank-of-ireland-uk');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('bank-of-ireland-uk-2', 'bnh', 'bank-of-ireland-uk');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('bank-of-ireland-uk-3', 'bristol and west', 'bank-of-ireland-uk');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('bank-of-ireland-uk-4', 'bristol & west', 'bank-of-ireland-uk');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('bank-of-ireland-uk-5', 'post office', 'bank-of-ireland-uk');
INSERT INTO providers (_id, name, iconRelativeUrl, colour) VALUES ('bank-of-scotland', 'Bank of Scotland', 'https://static-assets.isaeye.uk/default-bank-icons/bank-of-scotland.svg', '#05286a');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('bank-of-scotland-0', 'bos', 'bank-of-scotland');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('bank-of-scotland-1', 'banca na h-alba', 'bank-of-scotland');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('bank-of-scotland-2', 'alba', 'bank-of-scotland');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('bank-of-scotland-3', 'lloyds', 'bank-of-scotland');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('bank-of-scotland-4', 'hbos', 'bank-of-scotland');
INSERT INTO providers (_id, name, iconRelativeUrl, colour) VALUES ('barclays', 'Barclays', 'https://static-assets.isaeye.uk/default-bank-icons/barclays.svg', '#00aeef');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('barclays-0', 'barclay', 'barclays');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('barclays-1', 'barklays', 'barclays');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('barclays-2', 'barclay''s', 'barclays');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('barclays-3', 'woolwich', 'barclays');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('barclays-4', 'ing direct', 'barclays');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('barclays-5', 'tesco', 'barclays');
INSERT INTO providers (_id, name, iconRelativeUrl, colour) VALUES ('birmingham-midshires', 'Birmingham Midshires', 'https://static-assets.isaeye.uk/default-bank-icons/birmingham-midshires.svg', '#ee213b');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('birmingham-midshires-0', 'bm', 'birmingham-midshires');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('birmingham-midshires-1', 'brum', 'birmingham-midshires');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('birmingham-midshires-2', 'b mid', 'birmingham-midshires');
INSERT INTO providers (_id, name, iconRelativeUrl, colour) VALUES ('birmingham', 'Birmingham', 'https://static-assets.isaeye.uk/default-bank-icons/birmingham.svg', '#2c4ef7');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('birmingham-0', 'brum', 'birmingham');
INSERT INTO providers (_id, name, iconRelativeUrl, colour) VALUES ('blme', 'BLME', 'https://static-assets.isaeye.uk/default-bank-icons/blme.svg', '#003f5f');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('blme-0', 'bank of london & the middle east', 'blme');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('blme-1', 'boubyan', 'blme');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('blme-2', 'nomo', 'blme');
INSERT INTO providers (_id, name, iconRelativeUrl, colour) VALUES ('bny-mellon', 'BNY Mellon', 'https://static-assets.isaeye.uk/default-bank-icons/bny-mellon.svg', '#a49668');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('bny-mellon-0', 'bny', 'bny-mellon');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('bny-mellon-1', 'bnym', 'bny-mellon');
INSERT INTO providers (_id, name, iconRelativeUrl, colour) VALUES ('bradford-and-bingley', 'Bradford & Bingley', 'https://static-assets.isaeye.uk/default-bank-icons/bradford-and-bingley.svg', '#2d3192');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('bradford-and-bingley-0', 'b&m', 'bradford-and-bingley');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('bradford-and-bingley-1', 'bnm', 'bradford-and-bingley');
INSERT INTO providers (_id, name, iconRelativeUrl, colour) VALUES ('brewin-dolphin', 'Brewin Dolphin', 'https://static-assets.isaeye.uk/default-bank-icons/brewin-dolphin.svg', '#d3d3d3');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('brewin-dolphin-0', 'rbc', 'brewin-dolphin');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('brewin-dolphin-1', 'bd', 'brewin-dolphin');
INSERT INTO providers (_id, name, iconRelativeUrl, colour) VALUES ('brown-shipley', 'Brown Shipley', 'https://static-assets.isaeye.uk/default-bank-icons/brown-shipley.svg', '#00686b');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('brown-shipley-0', 'bs', 'brown-shipley');
INSERT INTO providers (_id, name, iconRelativeUrl, colour) VALUES ('cahoot', 'Cahoot', 'https://static-assets.isaeye.uk/default-bank-icons/cahoot.svg', '#6c207e');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('cahoot-0', 'santander', 'cahoot');
INSERT INTO providers (_id, name, iconRelativeUrl, colour) VALUES ('castle-trust', 'Castle Trust', 'https://static-assets.isaeye.uk/default-bank-icons/castle-trust.svg', '#152c49');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('castle-trust-0', 'ct', 'castle-trust');
INSERT INTO providers (_id, name, iconRelativeUrl, colour) VALUES ('cater-allen', 'Cater Allen', 'https://static-assets.isaeye.uk/default-bank-icons/cater-allen.svg', '#022151');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('cater-allen-0', 'ca', 'cater-allen');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('cater-allen-1', 'santander', 'cater-allen');
INSERT INTO providers (_id, name, iconRelativeUrl, colour) VALUES ('charity', 'Charity', 'https://static-assets.isaeye.uk/default-bank-icons/charity.svg', '#000000');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('charity-0', 'tcb', 'charity');
INSERT INTO providers (_id, name, iconRelativeUrl, colour) VALUES ('charter-savings', 'Charter Savings', 'https://static-assets.isaeye.uk/default-bank-icons/charter-savings.svg', '#0093d6');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('charter-savings-0', 'cs', 'charter-savings');
INSERT INTO providers (_id, name, iconRelativeUrl, colour) VALUES ('chase', 'Chase', 'https://static-assets.isaeye.uk/default-bank-icons/chase.svg', '#126bc5');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('chase-0', 'jpmorgan', 'chase');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('chase-1', 'jp morgan', 'chase');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('chase-2', 'jpm', 'chase');
INSERT INTO providers (_id, name, iconRelativeUrl, colour) VALUES ('cheltenham-and-gloucester', 'Cheltenham & Gloucester', 'https://static-assets.isaeye.uk/default-bank-icons/cheltenham-and-gloucester.svg', '#2b74b8');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('cheltenham-and-gloucester-0', 'c&g', 'cheltenham-and-gloucester');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('cheltenham-and-gloucester-1', 'c+g', 'cheltenham-and-gloucester');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('cheltenham-and-gloucester-2', 'lloyds', 'cheltenham-and-gloucester');
INSERT INTO providers (_id, name, iconRelativeUrl, colour) VALUES ('chip', 'Chip', 'https://static-assets.isaeye.uk/default-bank-icons/chip.svg', '#000000');
INSERT INTO providers (_id, name, iconRelativeUrl, colour) VALUES ('circa5000', 'Cira5000', 'https://static-assets.isaeye.uk/default-bank-icons/circa5000.svg', '#89f4ec');
INSERT INTO providers (_id, name, iconRelativeUrl, colour) VALUES ('close-brothers', 'Close Brothers', 'https://static-assets.isaeye.uk/default-bank-icons/close-brothers.svg', '#000a8b');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('close-brothers-0', 'cb', 'close-brothers');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('close-brothers-1', 'close bros', 'close-brothers');
INSERT INTO providers (_id, name, iconRelativeUrl, colour) VALUES ('cmc', 'CMC', 'https://static-assets.isaeye.uk/default-bank-icons/cmc.svg', '#03bbe1');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('cmc-0', 'deal4free', 'cmc');
INSERT INTO providers (_id, name, iconRelativeUrl, colour) VALUES ('coop-bank', 'The cooperative', 'https://static-assets.isaeye.uk/default-bank-icons/coop-bank.svg', '#23254f');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('coop-bank-0', 'coop', 'coop-bank');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('coop-bank-1', 'tcb', 'coop-bank');
INSERT INTO providers (_id, name, iconRelativeUrl, colour) VALUES ('coop-insurance-society', 'Co-operative Insurance Society', 'https://static-assets.isaeye.uk/default-bank-icons/coop-insurance-society.svg', '#003f4e');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('coop-insurance-society-0', 'coop', 'coop-insurance-society');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('coop-insurance-society-1', 'cis', 'coop-insurance-society');
INSERT INTO providers (_id, name, iconRelativeUrl, colour) VALUES ('coutts', 'Coutts', 'https://static-assets.isaeye.uk/default-bank-icons/coutts.svg', '#9e8d60');
INSERT INTO providers (_id, name, iconRelativeUrl, colour) VALUES ('credit-suisse', 'Credit Suisse', 'https://static-assets.isaeye.uk/default-bank-icons/credit-suisse.svg', '#003662');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('credit-suisse-0', 'cs', 'credit-suisse');
INSERT INTO providers (_id, name, iconRelativeUrl, colour) VALUES ('cynergy', 'Cynergy', 'https://static-assets.isaeye.uk/default-bank-icons/cynergy.svg', '#53c4a7');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('cynergy-0', 'bank of cyprus', 'cynergy');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('cynergy-1', 'boc', 'cynergy');
INSERT INTO providers (_id, name, iconRelativeUrl, colour) VALUES ('danske', 'Danske', 'https://static-assets.isaeye.uk/default-bank-icons/danske.svg', '#003f63');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('danske-0', 'national irish', 'danske');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('danske-1', 'ni', 'danske');
INSERT INTO providers (_id, name, iconRelativeUrl, colour) VALUES ('egg', 'Egg', 'https://static-assets.isaeye.uk/default-bank-icons/egg.svg', '#70b323');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('egg-0', 'yorkshire', 'egg');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('egg-1', 'ybs', 'egg');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('egg-2', 'prudential', 'egg');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('egg-3', 'citi', 'egg');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('egg-4', 'barclays', 'egg');
INSERT INTO providers (_id, name, iconRelativeUrl, colour) VALUES ('first-direct', 'First Direct', 'https://static-assets.isaeye.uk/default-bank-icons/first-direct.svg', '#000000');
INSERT INTO providers (_id, name, iconRelativeUrl, colour) VALUES ('ford', 'Ford Money', 'https://static-assets.isaeye.uk/default-bank-icons/ford.svg', '#00095b');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('ford-0', 'fm', 'ford');
INSERT INTO providers (_id, name, iconRelativeUrl, colour) VALUES ('foresters-friendly', 'Foresters Friendly', 'https://static-assets.isaeye.uk/default-bank-icons/foresters-friendly.svg', '#00635f');
INSERT INTO providers (_id, name, iconRelativeUrl, colour) VALUES ('freetrade', 'Freetrade', 'https://static-assets.isaeye.uk/default-bank-icons/freetrade.svg', '#f7618b');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('freetrade-0', 'ft', 'freetrade');
INSERT INTO providers (_id, name, iconRelativeUrl, colour) VALUES ('habib-zurich', 'Habib Zurich', 'https://static-assets.isaeye.uk/default-bank-icons/habib-zurich.svg', '#00664a');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('habib-zurich-0', 'hbzuk', 'habib-zurich');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('habib-zurich-1', 'hb', 'habib-zurich');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('habib-zurich-2', 'zurich', 'habib-zurich');
INSERT INTO providers (_id, name, iconRelativeUrl, colour) VALUES ('halifax', 'Halifax', 'https://static-assets.isaeye.uk/default-bank-icons/halifax.svg', '#005eb8');
INSERT INTO providers (_id, name, iconRelativeUrl, colour) VALUES ('hampshire-trust', 'Hampshire Trust', 'https://static-assets.isaeye.uk/default-bank-icons/hampshire-trust.svg', '#cd7537');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('hampshire-trust-0', 'ht', 'hampshire-trust');
INSERT INTO providers (_id, name, iconRelativeUrl, colour) VALUES ('handelsbanken', 'Handelsbanken', 'https://static-assets.isaeye.uk/default-bank-icons/handelsbanken.svg', '#005fa5');
INSERT INTO providers (_id, name, iconRelativeUrl, colour) VALUES ('hargreaves-lansdown', 'Hargreaves Lansdown', 'https://static-assets.isaeye.uk/default-bank-icons/hargreaves-lansdown.svg', '#071d49');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('hargreaves-lansdown-0', 'hl', 'hargreaves-lansdown');
INSERT INTO providers (_id, name, iconRelativeUrl, colour) VALUES ('healthy-investment', 'Healthy Investment', 'https://static-assets.isaeye.uk/default-bank-icons/healthy-investment.svg', '#57559c');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('healthy-investment-0', 'hi', 'healthy-investment');
INSERT INTO providers (_id, name, iconRelativeUrl, colour) VALUES ('hodge', 'Hodge', 'https://static-assets.isaeye.uk/default-bank-icons/hodge.svg', '#f4b700');
INSERT INTO providers (_id, name, iconRelativeUrl, colour) VALUES ('hoist', 'Hoist', 'https://static-assets.isaeye.uk/default-bank-icons/hoist.svg', '#b3267c');
INSERT INTO providers (_id, name, iconRelativeUrl, colour) VALUES ('hsbc', 'HSBC', 'https://static-assets.isaeye.uk/default-bank-icons/hsbc.svg', '#db0011');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('hsbc-0', '滙豐', 'hsbc');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('hsbc-1', 'hong kong', 'hsbc');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('hsbc-2', 'shanghai', 'hsbc');
INSERT INTO providers (_id, name, iconRelativeUrl, colour) VALUES ('icesave', 'Icesave', 'https://static-assets.isaeye.uk/default-bank-icons/icesave.svg', '#57b9e9');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('icesave-0', 'landsbanki', 'icesave');
INSERT INTO providers (_id, name, iconRelativeUrl, colour) VALUES ('ing-direct', 'ING Direct', 'https://static-assets.isaeye.uk/default-bank-icons/ing-direct.svg', '#ff6600');
INSERT INTO providers (_id, name, iconRelativeUrl, colour) VALUES ('intelligent-finance', 'Intelligent Finance', 'https://static-assets.isaeye.uk/default-bank-icons/intelligent-finance.svg', '#662374');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('intelligent-finance-0', 'if', 'intelligent-finance');
INSERT INTO providers (_id, name, iconRelativeUrl, colour) VALUES ('investec', 'Investec', 'https://static-assets.isaeye.uk/default-bank-icons/investec.svg', '#0b1742');
INSERT INTO providers (_id, name, iconRelativeUrl, colour) VALUES ('investengine', 'InvestEngine', 'https://static-assets.isaeye.uk/default-bank-icons/investengine.svg', '#3b3bf5');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('investengine-0', 'ie', 'investengine');
INSERT INTO providers (_id, name, iconRelativeUrl, colour) VALUES ('jamaica-national', 'Jamaica National', 'https://static-assets.isaeye.uk/default-bank-icons/jamaica-national.svg', '#0053a0');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('jamaica-national-0', 'jnb', 'jamaica-national');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('jamaica-national-1', 'jn', 'jamaica-national');
INSERT INTO providers (_id, name, iconRelativeUrl, colour) VALUES ('kent-reliance', 'Kent Reliance', 'https://static-assets.isaeye.uk/default-bank-icons/kent-reliance.svg', '#50213f');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('kent-reliance-0', 'kr', 'kent-reliance');
INSERT INTO providers (_id, name, iconRelativeUrl, colour) VALUES ('kroo', 'Kroo', 'https://static-assets.isaeye.uk/default-bank-icons/kroo.svg', '#e3176f');
INSERT INTO providers (_id, name, iconRelativeUrl, colour) VALUES ('lhv', 'LHV', 'https://static-assets.isaeye.uk/default-bank-icons/lhv.svg', '#202020');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('lhv-0', 'lõhmus haavel viisemann', 'lhv');
INSERT INTO providers (_id, name, iconRelativeUrl, colour) VALUES ('lic-india', 'Life Insurance Corporation of India', 'https://static-assets.isaeye.uk/default-bank-icons/life-insurance-corp-india.svg', '#f8c301');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('lic-india-0', 'lic', 'lic-india');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('lic-india-1', 'lici', 'lic-india');
INSERT INTO providers (_id, name, iconRelativeUrl, colour) VALUES ('lightyear', 'Lightyear', 'https://static-assets.isaeye.uk/default-bank-icons/lightyear.svg', '#4e6abf');
INSERT INTO providers (_id, name, iconRelativeUrl, colour) VALUES ('lloyds-tsb', 'Lloyds TSB', 'https://static-assets.isaeye.uk/default-bank-icons/lloyds-tsb.svg', '#2a74ba');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('lloyds-tsb-0', 'ltsb', 'lloyds-tsb');
INSERT INTO providers (_id, name, iconRelativeUrl, colour) VALUES ('lloyds', 'Lloyds', 'https://static-assets.isaeye.uk/default-bank-icons/lloyds.svg', '#11b67a');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('lloyds-0', 'tsb', 'lloyds');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('lloyds-1', 'loyds', 'lloyds');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('lloyds-2', 'loids', 'lloyds');
INSERT INTO providers (_id, name, iconRelativeUrl, colour) VALUES ('london-victoria', 'LV', 'https://static-assets.isaeye.uk/default-bank-icons/london-victoria.svg', '#b6cc00');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('london-victoria-0', 'london victoria', 'london-victoria');
INSERT INTO providers (_id, name, iconRelativeUrl, colour) VALUES ('marcus', 'Marcus', 'https://static-assets.isaeye.uk/default-bank-icons/marcus.svg', '#22263f');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('marcus-0', 'goldman sachs', 'marcus');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('marcus-1', 'gs', 'marcus');
INSERT INTO providers (_id, name, iconRelativeUrl, colour) VALUES ('marks-and-spencers', 'M&S', 'https://static-assets.isaeye.uk/default-bank-icons/marks-and-spencers.svg', '#000000');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('marks-and-spencers-0', 'm-s', 'marks-and-spencers');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('marks-and-spencers-1', 'marks', 'marks-and-spencers');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('marks-and-spencers-2', 'spencer', 'marks-and-spencers');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('marks-and-spencers-3', 'ms', 'marks-and-spencers');
INSERT INTO providers (_id, name, iconRelativeUrl, colour) VALUES ('mbna', 'MBNA', 'https://static-assets.isaeye.uk/default-bank-icons/mbna.svg', '#107987');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('mbna-0', 'maryland', 'mbna');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('mbna-1', 'lloyds', 'mbna');
INSERT INTO providers (_id, name, iconRelativeUrl, colour) VALUES ('metlife', 'Metlife', 'https://static-assets.isaeye.uk/default-bank-icons/metlife.svg', '#afcb3a');
INSERT INTO providers (_id, name, iconRelativeUrl, colour) VALUES ('metro', 'Metro', 'https://static-assets.isaeye.uk/default-bank-icons/metro.svg', '#2548af');
INSERT INTO providers (_id, name, iconRelativeUrl, colour) VALUES ('moneybox', 'Moneybox', 'https://static-assets.isaeye.uk/default-bank-icons/moneybox.svg', '#58c4c6');
INSERT INTO providers (_id, name, iconRelativeUrl, colour) VALUES ('moneyfarm', 'Moneyfarm', 'https://static-assets.isaeye.uk/default-bank-icons/moneyfarm.svg', '#320327');
INSERT INTO providers (_id, name, iconRelativeUrl, colour) VALUES ('monument', 'Monument', 'https://static-assets.isaeye.uk/default-bank-icons/monument.svg', '#004048');
INSERT INTO providers (_id, name, iconRelativeUrl, colour) VALUES ('monzo', 'Monzo', 'https://static-assets.isaeye.uk/default-bank-icons/monzo.svg', '#112231');
INSERT INTO providers (_id, name, iconRelativeUrl, colour) VALUES ('national-savings-and-investments', 'NS&I', 'https://static-assets.isaeye.uk/default-bank-icons/national-savings-and-investments.svg', '#00585c');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('national-savings-and-investments-0', 'ns-i', 'national-savings-and-investments');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('national-savings-and-investments-1', 'nsi', 'national-savings-and-investments');
INSERT INTO providers (_id, name, iconRelativeUrl, colour) VALUES ('nationwide', 'Nationwide', 'https://static-assets.isaeye.uk/default-bank-icons/nationwide.svg', '#011546');
INSERT INTO providers (_id, name, iconRelativeUrl, colour) VALUES ('natwest', 'NatWest', 'https://static-assets.isaeye.uk/default-bank-icons/natwest.svg', '#3c1053');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('natwest-0', 'national westminster', 'natwest');
INSERT INTO providers (_id, name, iconRelativeUrl, colour) VALUES ('nfu-mutual', 'NFU Mutual', 'https://static-assets.isaeye.uk/default-bank-icons/nfu-mutual.svg', '#f7ca32');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('nfu-mutual-0', 'nfum', 'nfu-mutual');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('nfu-mutual-1', 'national farmers union', 'nfu-mutual');
INSERT INTO providers (_id, name, iconRelativeUrl, colour) VALUES ('northern-rock', 'Northern Rock', 'https://static-assets.isaeye.uk/default-bank-icons/northern-rock.svg', '#eb008c');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('northern-rock-0', 'nr', 'northern-rock');
INSERT INTO providers (_id, name, iconRelativeUrl, colour) VALUES ('northern', 'Northern', 'https://static-assets.isaeye.uk/default-bank-icons/northern.svg', '#0d2a9e');
INSERT INTO providers (_id, name, iconRelativeUrl, colour) VALUES ('nutmeg', 'Nutmeg', 'https://static-assets.isaeye.uk/default-bank-icons/nutmeg.svg', '#2fb053');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('nutmeg-0', 'jpm', 'nutmeg');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('nutmeg-1', 'jp morgan', 'nutmeg');
INSERT INTO providers (_id, name, iconRelativeUrl, colour) VALUES ('oak-north', 'Oak North', 'https://static-assets.isaeye.uk/default-bank-icons/oak-north.svg', '#2adaa5');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('oak-north-0', 'on', 'oak-north');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('oak-north-1', 'oaknorth', 'oak-north');
INSERT INTO providers (_id, name, iconRelativeUrl, colour) VALUES ('octopus-investments', 'Octopus Investments', 'https://static-assets.isaeye.uk/default-bank-icons/octopus-investments.svg', '#100030');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('octopus-investments-0', 'oi', 'octopus-investments');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('octopus-investments-1', 'octo', 'octopus-investments');
INSERT INTO providers (_id, name, iconRelativeUrl, colour) VALUES ('one-family', 'One Family', 'https://static-assets.isaeye.uk/default-bank-icons/onefamily.svg', '#1e193e');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('one-family-0', 'of', 'one-family');
INSERT INTO providers (_id, name, iconRelativeUrl, colour) VALUES ('oxbury', 'Oxbury', 'https://static-assets.isaeye.uk/default-bank-icons/oxbury.svg', '#0ea149');
INSERT INTO providers (_id, name, iconRelativeUrl, colour) VALUES ('paragon', 'Paragon', 'https://static-assets.isaeye.uk/default-bank-icons/paragon.svg', '#75c92b');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('paragon-0', 'paragon bank', 'paragon');
INSERT INTO providers (_id, name, iconRelativeUrl, colour) VALUES ('phoenix-life', 'Phoenix Life', 'https://static-assets.isaeye.uk/default-bank-icons/phoenix-life.svg', '#e2066f');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('phoenix-life-0', 'pl', 'phoenix-life');
INSERT INTO providers (_id, name, iconRelativeUrl, colour) VALUES ('plum', 'Plum', 'https://static-assets.isaeye.uk/default-bank-icons/plum.svg', '#1a0a2b');
INSERT INTO providers (_id, name, iconRelativeUrl, colour) VALUES ('post-office', 'Post Office', 'https://static-assets.isaeye.uk/default-bank-icons/post-office.svg', '#d71440');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('post-office-0', 'post office money', 'post-office');
INSERT INTO providers (_id, name, iconRelativeUrl, colour) VALUES ('prosper', 'Prosper', 'https://static-assets.isaeye.uk/default-bank-icons/prosper.svg', '#000000');
INSERT INTO providers (_id, name, iconRelativeUrl, colour) VALUES ('punjab-national', 'Punjab National', 'https://static-assets.isaeye.uk/default-bank-icons/punjab-national.svg', '#9f1a45');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('punjab-national-0', 'pn', 'punjab-national');
INSERT INTO providers (_id, name, iconRelativeUrl, colour) VALUES ('qib', 'QIB', 'https://static-assets.isaeye.uk/default-bank-icons/qib.svg', '#0075b0');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('qib-0', 'qatar islamic', 'qib');
INSERT INTO providers (_id, name, iconRelativeUrl, colour) VALUES ('quilter', 'Quilter', 'https://static-assets.isaeye.uk/default-bank-icons/quilter.svg', '#0f7b3f');
INSERT INTO providers (_id, name, iconRelativeUrl, colour) VALUES ('raisin', 'Raisin', 'https://static-assets.isaeye.uk/default-bank-icons/raisin.svg', '#156cc4');
INSERT INTO providers (_id, name, iconRelativeUrl, colour) VALUES ('rbc-brewin-dolphin', 'RBC Brewin Dolphin', 'https://static-assets.isaeye.uk/default-bank-icons/rbc-brewin-dolphin.svg', '#0059b3');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('rbc-brewin-dolphin-0', 'rbc', 'rbc-brewin-dolphin');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('rbc-brewin-dolphin-1', 'bd', 'rbc-brewin-dolphin');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('rbc-brewin-dolphin-2', 'brewin', 'rbc-brewin-dolphin');
INSERT INTO providers (_id, name, iconRelativeUrl, colour) VALUES ('rbs', 'RBS', 'https://static-assets.isaeye.uk/default-bank-icons/rbs-ulster.svg', '#3c1053');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('rbs-0', 'royal bank of scotland', 'rbs');
INSERT INTO providers (_id, name, iconRelativeUrl, colour) VALUES ('rci', 'RCI', 'https://static-assets.isaeye.uk/default-bank-icons/rci.svg', '#41d7eb');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('rci-0', 'renault', 'rci');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('rci-1', 'mobilize', 'rci');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('rci-2', 'nissan', 'rci');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('rci-3', 'dacia', 'rci');
INSERT INTO providers (_id, name, iconRelativeUrl, colour) VALUES ('royal-london', 'Royal London', 'https://static-assets.isaeye.uk/default-bank-icons/royal-london.svg', '#470054');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('royal-london-0', 'rl', 'royal-london');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('royal-london-1', 'cis', 'royal-london');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('royal-london-2', 'coop', 'royal-london');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('royal-london-3', 'abbey', 'royal-london');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('royal-london-4', 'santander', 'royal-london');
INSERT INTO providers (_id, name, iconRelativeUrl, colour) VALUES ('saga', 'Saga', 'https://static-assets.isaeye.uk/default-bank-icons/saga.svg', '#1e3282');
INSERT INTO providers (_id, name, iconRelativeUrl, colour) VALUES ('sainsburys', 'Sainsbury''s', 'https://static-assets.isaeye.uk/default-bank-icons/sainsburys.svg', '#f06c00');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('sainsburys-0', 'sainsburys', 'sainsburys');
INSERT INTO providers (_id, name, iconRelativeUrl, colour) VALUES ('santander', 'Santander', 'https://static-assets.isaeye.uk/default-bank-icons/santander.svg', '#ec0000');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('santander-0', 'abbey national', 'santander');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('santander-1', 'satander', 'santander');
INSERT INTO providers (_id, name, iconRelativeUrl, colour) VALUES ('schroders', 'Schroders', 'https://static-assets.isaeye.uk/default-bank-icons/schroders.svg', '#001e41');
INSERT INTO providers (_id, name, iconRelativeUrl, colour) VALUES ('scottish-friendly', 'Scottish Friendly', 'https://static-assets.isaeye.uk/default-bank-icons/scottish-friendly.svg', '#472f92');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('scottish-friendly-0', 'sf', 'scottish-friendly');
INSERT INTO providers (_id, name, iconRelativeUrl, colour) VALUES ('secure-trust', 'Secure Trust', 'https://static-assets.isaeye.uk/default-bank-icons/secure-trust.svg', '#003a67');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('secure-trust-0', 'st', 'secure-trust');
INSERT INTO providers (_id, name, iconRelativeUrl, colour) VALUES ('shawbrook', 'Shawbrook', 'https://static-assets.isaeye.uk/default-bank-icons/shawbrook.svg', '#e10a93');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('shawbrook-0', 'sb', 'shawbrook');
INSERT INTO providers (_id, name, iconRelativeUrl, colour) VALUES ('shepherds-friendly', 'Shepherds Friendly', 'https://static-assets.isaeye.uk/default-bank-icons/shepherds-friendly.svg', '#f7a900');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('shepherds-friendly-0', 'sf', 'shepherds-friendly');
INSERT INTO providers (_id, name, iconRelativeUrl, colour) VALUES ('skandia', 'Skandia', 'https://static-assets.isaeye.uk/default-bank-icons/skandia.svg', '#005da8');
INSERT INTO providers (_id, name, iconRelativeUrl, colour) VALUES ('societe-generale', 'Société Générale', 'https://static-assets.isaeye.uk/default-bank-icons/societe-generale.svg', '#e90031');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('societe-generale-0', 'sg', 'societe-generale');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('societe-generale-1', 'societe generale', 'societe-generale');
INSERT INTO providers (_id, name, iconRelativeUrl, colour) VALUES ('standard-life', 'Standard Life', 'https://static-assets.isaeye.uk/default-bank-icons/standard-life.svg', '#0a2f73');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('standard-life-0', 'sl', 'standard-life');
INSERT INTO providers (_id, name, iconRelativeUrl, colour) VALUES ('starling', 'Starling', 'https://static-assets.isaeye.uk/default-bank-icons/starling.svg', '#6935d3');
INSERT INTO providers (_id, name, iconRelativeUrl, colour) VALUES ('state-bank-of-india', 'SBI', 'https://static-assets.isaeye.uk/default-bank-icons/state-bank-of-india.svg', '#2cb9f1');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('state-bank-of-india-0', 'state bank of india', 'state-bank-of-india');
INSERT INTO providers (_id, name, iconRelativeUrl, colour) VALUES ('stratiphy', 'Stratiphy', 'https://static-assets.isaeye.uk/default-bank-icons/stratiphy.svg', '#6640ff');
INSERT INTO providers (_id, name, iconRelativeUrl, colour) VALUES ('strowz', 'Strowz', 'https://static-assets.isaeye.uk/default-bank-icons/strowz.svg', '#140323');
INSERT INTO providers (_id, name, iconRelativeUrl, colour) VALUES ('tesco', 'Tesco', 'https://static-assets.isaeye.uk/default-bank-icons/tesco.svg', '#0053a1');
INSERT INTO providers (_id, name, iconRelativeUrl, colour) VALUES ('trading-212', 'Trading 212', 'https://static-assets.isaeye.uk/default-bank-icons/trading-212.svg', '#00a7e1');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('trading-212-0', 't212', 'trading-212');
INSERT INTO providers (_id, name, iconRelativeUrl, colour) VALUES ('transport-friendly', 'Transport Friendly', 'https://static-assets.isaeye.uk/default-bank-icons/transport-friendly.svg', '#214393');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('transport-friendly-0', 'tf', 'transport-friendly');
INSERT INTO providers (_id, name, iconRelativeUrl, colour) VALUES ('triodos', 'Triodos', 'https://static-assets.isaeye.uk/default-bank-icons/triodos.svg', '#00937b');
INSERT INTO providers (_id, name, iconRelativeUrl, colour) VALUES ('tsb', 'TSB', 'https://static-assets.isaeye.uk/default-bank-icons/tsb.svg', '#00a8e1');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('tsb-0', 'trustee savings bank', 'tsb');
INSERT INTO providers (_id, name, iconRelativeUrl, colour) VALUES ('united-national', 'United National', 'https://static-assets.isaeye.uk/default-bank-icons/united-national.svg', '#0083ca');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('united-national-0', 'un', 'united-national');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('united-national-1', 'ubl', 'united-national');
INSERT INTO providers (_id, name, iconRelativeUrl, colour) VALUES ('united-trust', 'United Trust', 'https://static-assets.isaeye.uk/default-bank-icons/united-trust.svg', '#ffcf00');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('united-trust-0', 'ut', 'united-trust');
INSERT INTO providers (_id, name, iconRelativeUrl, colour) VALUES ('ulster', 'Ulster', 'https://static-assets.isaeye.uk/default-bank-icons/rbs-ulster.svg', '#3c1053');
INSERT INTO providers (_id, name, iconRelativeUrl, colour) VALUES ('vanguard', 'Vanguard', 'https://static-assets.isaeye.uk/default-bank-icons/vanguard.svg', '#96151d');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('vanguard-0', 'vg', 'vanguard');
INSERT INTO providers (_id, name, iconRelativeUrl, colour) VALUES ('vanquis', 'Vanquis', 'https://static-assets.isaeye.uk/default-bank-icons/vanquis.svg', '#006edc');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('vanquis-0', 'vq', 'vanquis');
INSERT INTO providers (_id, name, iconRelativeUrl, colour) VALUES ('vida', 'Vida', 'https://static-assets.isaeye.uk/default-bank-icons/vida.svg', '#00003b');
INSERT INTO providers (_id, name, iconRelativeUrl, colour) VALUES ('virgin', 'Virgin', 'https://static-assets.isaeye.uk/default-bank-icons/virgin.svg', '#e10a0a');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('virgin-0', 'vm', 'virgin');
INSERT INTO providers (_id, name, iconRelativeUrl, colour) VALUES ('wealthify', 'Wealthify', 'https://static-assets.isaeye.uk/default-bank-icons/wealthify.svg', '#53c0b1');
INSERT INTO providers (_id, name, iconRelativeUrl, colour) VALUES ('wealthtime', 'Wealthtime', 'https://static-assets.isaeye.uk/default-bank-icons/wealthtime.svg', '#1dd698');
INSERT INTO providers (_id, name, iconRelativeUrl, colour) VALUES ('xtb', 'XTB', 'https://static-assets.isaeye.uk/default-bank-icons/xtb.svg', '#fe0103');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('xtb-0', 'x trade brokers', 'xtb');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('xtb-1', 'x-trade', 'xtb');
INSERT INTO providers (_id, name, iconRelativeUrl, colour) VALUES ('zenith', 'Zenith', 'https://static-assets.isaeye.uk/default-bank-icons/zenith.svg', '#ed1c24');
INSERT INTO providers (_id, name, iconRelativeUrl, colour) VALUES ('zopa', 'Zopa', 'https://static-assets.isaeye.uk/default-bank-icons/zopa.svg', '#72e7c1');
INSERT INTO providers (_id, name, iconRelativeUrl, colour) VALUES ('habib', 'Habib', 'https://static-assets.isaeye.uk/default-bank-icons/habib.svg', '#008269');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('habib-0', 'hbp', 'habib');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('habib-1', 'hbl', 'habib');
INSERT INTO providers (_id, name, iconRelativeUrl, colour) VALUES ('bpi', 'Bank of the Philippine Islands', 'https://static-assets.isaeye.uk/default-bank-icons/bpi.svg', '#008269');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('bpi-0', 'bpi', 'bpi');
INSERT INTO providers (_id, name, iconRelativeUrl, colour) VALUES ('nb-egypt', 'National Bank of Egypt', 'https://static-assets.isaeye.uk/default-bank-icons/nb-egypt.svg', '#fc8508');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('nb-egypt-0', 'nbe', 'nb-egypt');
INSERT INTO providers (_id, name, iconRelativeUrl, colour) VALUES ('ziraat', 'Ziraat', 'https://static-assets.isaeye.uk/default-bank-icons/ziraat.svg', '#cc2229');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('ziraat-0', 'bankası', 'ziraat');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('ziraat-1', 'tcb', 'ziraat');
INSERT INTO providers (_id, name, iconRelativeUrl, colour) VALUES ('skipton', 'Skipton', 'https://static-assets.isaeye.uk/default-bank-icons/skipton.svg', '#0072c5');
INSERT INTO providers (_id, name, iconRelativeUrl, colour) VALUES ('isbank', 'İşbank', 'https://static-assets.isaeye.uk/default-bank-icons/isbank.svg', '#00428a');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('isbank-0', 'Türkiye İş Bankası', 'isbank');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('isbank-1', 'tib', 'isbank');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('isbank-2', 'Business Bank of Turkey', 'isbank');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('isbank-3', 'bbt', 'isbank');
INSERT INTO providers (_id, name, iconRelativeUrl, colour) VALUES ('bank-of-ceylon', 'Bank of Ceylon', 'https://static-assets.isaeye.uk/default-bank-icons/bank-of-ceylon.svg', '#ffc805');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('bank-of-ceylon-0', 'boc', 'bank-of-ceylon');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('bank-of-ceylon-1', 'sri lanka', 'bank-of-ceylon');
INSERT INTO providers (_id, name, iconRelativeUrl, colour) VALUES ('british-arab-commercial', 'BACB', 'https://static-assets.isaeye.uk/default-bank-icons/british-arab-commercial.svg', '#00a7cf');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('british-arab-commercial-0', 'ubaf', 'british-arab-commercial');
INSERT INTO providers (_id, name, iconRelativeUrl, colour) VALUES ('first-city-monument', 'First City Monument', 'https://static-assets.isaeye.uk/default-bank-icons/first-city-monument.svg', '#6f3f96');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('first-city-monument-0', 'fcmb', 'first-city-monument');
INSERT INTO providers (_id, name, iconRelativeUrl, colour) VALUES ('st-james-place', 'St James''s Place', 'https://static-assets.isaeye.uk/default-bank-icons/st-james-place.svg', '#0a1428');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('st-james-place-0', 'sjp', 'st-james-place');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('st-james-place-1', 'st james'' place', 'st-james-place');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('st-james-place-2', 'st james place', 'st-james-place');
INSERT INTO providers (_id, name, iconRelativeUrl, colour) VALUES ('m-and-g', 'M&G', 'https://static-assets.isaeye.uk/default-bank-icons/m-and-g.svg', '#2f6167');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('m-and-g-0', 'm and g', 'm-and-g');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('m-and-g-1', 'm & g', 'm-and-g');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('m-and-g-2', 'monument & general', 'm-and-g');
INSERT INTO providers (_id, name, iconRelativeUrl, colour) VALUES ('interactive-investor', 'Interactive Investor', 'https://static-assets.isaeye.uk/default-bank-icons/interactive-investor.svg', '#0023e6');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('interactive-investor-0', 'ii', 'interactive-investor');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('interactive-investor-1', 'ample', 'interactive-investor');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('interactive-investor-2', 'aberdeen', 'interactive-investor');
INSERT INTO providers (_id, name, iconRelativeUrl, colour) VALUES ('gatehouse', 'Gatehouse', 'https://static-assets.isaeye.uk/default-bank-icons/gatehouse.svg', '#a6c236');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('gatehouse-0', 'gh', 'gatehouse');
INSERT INTO providers (_id, name, iconRelativeUrl, colour) VALUES ('smile', 'smile', 'https://static-assets.isaeye.uk/default-bank-icons/smile.svg', '#ff3399');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('smile-0', 'coop', 'smile');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('smile-1', 'the co-operative', 'smile');
INSERT INTO providers (_id, name, iconRelativeUrl, colour) VALUES ('charles-stanley', 'Charles Stanley', 'https://static-assets.isaeye.uk/default-bank-icons/charles-stanley.svg', '#000b49');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('charles-stanley-0', 'cs', 'charles-stanley');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('charles-stanley-1', 'raymond james', 'charles-stanley');
INSERT INTO providers (_id, name, iconRelativeUrl, colour) VALUES ('streambank', 'StreamBank', 'https://static-assets.isaeye.uk/default-bank-icons/streambank.svg', '#0e786e');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('streambank-0', 'sb', 'streambank');
INSERT INTO providers (_id, name, iconRelativeUrl, colour) VALUES ('castle-community', 'Castle Community', 'https://static-assets.isaeye.uk/default-bank-icons/castle-community.svg', '#ef1c2f');
INSERT INTO providerAliases (_id, alias, providerId) VALUES ('castle-community-0', 'ccb', 'castle-community');
INSERT INTO providers (_id, name, iconRelativeUrl, colour) VALUES ('prudential', 'Prudential', 'https://static-assets.isaeye.uk/default-bank-icons/prudential.svg', '#e72139');
INSERT INTO rulesetExceptions (_id, productTypeId, rulesetId, allowancePence, notes, includedInShared) VALUES ('2017/2018-HELP_TO_BUY', 'HELP_TO_BUY', '2017/2018', 240000, 'Contribute up to £200 a month, and up to £1,200 in the first month.', 1);
INSERT INTO rulesetExceptions (_id, productTypeId, rulesetId, allowancePence, notes, includedInShared) VALUES ('2017/2018-LIFETIME', 'LIFETIME', '2017/2018', 400000, NULL, 1);
INSERT INTO rulesetExceptions (_id, productTypeId, rulesetId, allowancePence, notes, includedInShared) VALUES ('2017/2018-JUNIOR', 'JUNIOR', '2017/2018', 412800, NULL, 0);
INSERT INTO rulesetExceptions (_id, productTypeId, rulesetId, allowancePence, notes, includedInShared) VALUES ('2018/2019-HELP_TO_BUY', 'HELP_TO_BUY', '2018/2019', 240000, 'Contribute up to £200 a month, and up to £1,200 in the first month.', 1);
INSERT INTO rulesetExceptions (_id, productTypeId, rulesetId, allowancePence, notes, includedInShared) VALUES ('2018/2019-LIFETIME', 'LIFETIME', '2018/2019', 400000, NULL, 1);
INSERT INTO rulesetExceptions (_id, productTypeId, rulesetId, allowancePence, notes, includedInShared) VALUES ('2018/2019-JUNIOR', 'JUNIOR', '2018/2019', 412800, NULL, 0);
INSERT INTO rulesetExceptions (_id, productTypeId, rulesetId, allowancePence, notes, includedInShared) VALUES ('2019/2020-HELP_TO_BUY', 'HELP_TO_BUY', '2019/2020', 240000, 'Contribute up to £200 a month, and up to £1,200 in the first month.', 1);
INSERT INTO rulesetExceptions (_id, productTypeId, rulesetId, allowancePence, notes, includedInShared) VALUES ('2019/2020-LIFETIME', 'LIFETIME', '2019/2020', 400000, NULL, 1);
INSERT INTO rulesetExceptions (_id, productTypeId, rulesetId, allowancePence, notes, includedInShared) VALUES ('2019/2020-JUNIOR', 'JUNIOR', '2019/2020', 436800, NULL, 0);
INSERT INTO rulesetExceptions (_id, productTypeId, rulesetId, allowancePence, notes, includedInShared) VALUES ('2020/2021-HELP_TO_BUY', 'HELP_TO_BUY', '2020/2021', 240000, 'Contribute up to £200 a month, and up to £1,200 in the first month.', 1);
INSERT INTO rulesetExceptions (_id, productTypeId, rulesetId, allowancePence, notes, includedInShared) VALUES ('2020/2021-LIFETIME', 'LIFETIME', '2020/2021', 400000, NULL, 1);
INSERT INTO rulesetExceptions (_id, productTypeId, rulesetId, allowancePence, notes, includedInShared) VALUES ('2020/2021-JUNIOR', 'JUNIOR', '2020/2021', 900000, NULL, 0);
INSERT INTO rulesetExceptions (_id, productTypeId, rulesetId, allowancePence, notes, includedInShared) VALUES ('2021/2022-HELP_TO_BUY', 'HELP_TO_BUY', '2021/2022', 240000, 'Contribute up to £200 a month, and up to £1,200 in the first month.', 1);
INSERT INTO rulesetExceptions (_id, productTypeId, rulesetId, allowancePence, notes, includedInShared) VALUES ('2021/2022-LIFETIME', 'LIFETIME', '2021/2022', 400000, NULL, 1);
INSERT INTO rulesetExceptions (_id, productTypeId, rulesetId, allowancePence, notes, includedInShared) VALUES ('2021/2022-JUNIOR', 'JUNIOR', '2021/2022', 900000, NULL, 0);
INSERT INTO rulesetExceptions (_id, productTypeId, rulesetId, allowancePence, notes, includedInShared) VALUES ('2022/2023-HELP_TO_BUY', 'HELP_TO_BUY', '2022/2023', 240000, 'Contribute up to £200 a month, and up to £1,200 in the first month.', 1);
INSERT INTO rulesetExceptions (_id, productTypeId, rulesetId, allowancePence, notes, includedInShared) VALUES ('2022/2023-LIFETIME', 'LIFETIME', '2022/2023', 400000, NULL, 1);
INSERT INTO rulesetExceptions (_id, productTypeId, rulesetId, allowancePence, notes, includedInShared) VALUES ('2022/2023-JUNIOR', 'JUNIOR', '2022/2023', 900000, NULL, 0);
INSERT INTO rulesetExceptions (_id, productTypeId, rulesetId, allowancePence, notes, includedInShared) VALUES ('2023/2024-HELP_TO_BUY', 'HELP_TO_BUY', '2023/2024', 240000, 'Contribute up to £200 a month, and up to £1,200 in the first month.', 1);
INSERT INTO rulesetExceptions (_id, productTypeId, rulesetId, allowancePence, notes, includedInShared) VALUES ('2023/2024-LIFETIME', 'LIFETIME', '2023/2024', 400000, NULL, 1);
INSERT INTO rulesetExceptions (_id, productTypeId, rulesetId, allowancePence, notes, includedInShared) VALUES ('2023/2024-JUNIOR', 'JUNIOR', '2023/2024', 900000, NULL, 0);
INSERT INTO rulesetExceptions (_id, productTypeId, rulesetId, allowancePence, notes, includedInShared) VALUES ('2024/2025-HELP_TO_BUY', 'HELP_TO_BUY', '2024/2025', 240000, 'Contribute up to £200 a month, and up to £1,200 in the first month.', 1);
INSERT INTO rulesetExceptions (_id, productTypeId, rulesetId, allowancePence, notes, includedInShared) VALUES ('2024/2025-LIFETIME', 'LIFETIME', '2024/2025', 400000, NULL, 1);
INSERT INTO rulesetExceptions (_id, productTypeId, rulesetId, allowancePence, notes, includedInShared) VALUES ('2024/2025-JUNIOR', 'JUNIOR', '2024/2025', 900000, NULL, 0);
INSERT INTO rulesetExceptions (_id, productTypeId, rulesetId, allowancePence, notes, includedInShared) VALUES ('2025/2026-HELP_TO_BUY', 'HELP_TO_BUY', '2025/2026', 240000, 'Contribute up to £200 a month, and up to £1,200 in the first month.', 1);
INSERT INTO rulesetExceptions (_id, productTypeId, rulesetId, allowancePence, notes, includedInShared) VALUES ('2025/2026-LIFETIME', 'LIFETIME', '2025/2026', 400000, NULL, 1);
INSERT INTO rulesetExceptions (_id, productTypeId, rulesetId, allowancePence, notes, includedInShared) VALUES ('2025/2026-JUNIOR', 'JUNIOR', '2025/2026', 900000, NULL, 0);
